### ISSUE TITLE
A sort of sections on page refresh

### ISSUE THREAD

**Issue by Jrizzi1** [rmurphey/js-assessment#108] opened 2015-05-08 15:14 UTC
every time i refresh, i have to find my section again that i was working on, which is sometimes not an easy feat...maybe a sort applied to the sections of testing?

**Comment by ashleygwilliams** [comment] 2015-05-08 15:40
hi @Jrizzi1 ! this is a duplicate of #61 - the tests are in a random order because they are loaded using `require`. 

a few weeks ago we decided to close the issue- but we are currently working on some rewrites as we move to a major version release, and i think that this is at least worth reconsidering. i can empathize with getting disoriented!

@jmeas @kadamwhite thoughts?

**Comment by ashleygwilliams** [comment] 2015-05-08 15:40
OH ALSO: thank you so much for contributing an issue, @Jrizzi1 :+1:

**Comment by jmeas** [comment] 2015-05-08 15:52
I'm thinking we could potentially just get rid of require altogether. What we would do instead is just type out the filenames manually in [the test file](https://github.com/rmurphey/js-assessment/blob/master/tests/runner.html#L22) and use browser globals.

Loading each script manually is old-school, and using browser globals is bad practice, but in this case it works really well, I think. Because of the fact the app files are stubbed out, nobody will need to go in and add new script tags when they clone this lib to write some code. Also, the browser globals will already be added by us in those stubs.

The only time someone would need to change this is if they planned to add new tests, and an instruction on how to do that would be easy to add to the README, I think.

What we get in exchange for those two inconveniences are:

1. assurance that the tests load in the same order, always
2. removal of unnecessary [AMD wrapper code](https://github.com/rmurphey/js-assessment/blob/master/app/arrays.js#L1-L4)
3. removal of [the require config file](https://github.com/rmurphey/js-assessment/blob/master/app/config.js)

Thoughtz?

**Comment by ashleygwilliams** [comment] 2015-05-08 16:10
yeah i am so into this

**Comment by jmeas** [comment] 2015-05-08 16:23
I can try to put together a PR tonight!

**Comment by ashleygwilliams** [comment] 2015-05-08 16:42
cool. i'mma ship the new browser deps stuff soon, so there shouldn't be a conflict.

**Comment by ashleygwilliams** [comment] 2015-05-09 15:59
yo @jmeas - did you get to this yet? if not i might try to tackle it tonight cuz it's blocking

**Comment by jacobroufa** [comment] 2015-05-12 20:28
This should be fixed by #112. :+1:

**Comment by ashleygwilliams** [comment] 2015-05-12 22:21
solved with #112, closing

**Closed by ashleygwilliams** 2015-05-12 22:21 UTC
Labels: duplicate, enhancement, question
